a = list(range(10))
print(a)
b = list(range(10, 21))
print(b)
c = list(range(10, 0, -1))
print(c)
sum = sum(range(1, 4))
print(sum)
d,f,g = range(5,8)
print(d,f,g)
m = iter('hi')
print(next(m))
for i in range(4):
    print(i)